% ===========================
%  📌 Define Paths for Different Atlas Stages
% ===========================

% Define paths for different templates
templates = struct( ...
    'adult', struct( ...
        'template', 'template_volume_10um.npy', ...
        'annotation', 'annotation_volume_10um_by_index.npy', ...
        'structure_tree', 'structure_tree_safe_2017.csv', ...
        'brain', '997.mat' ...
    ), ...
    'P4', struct( ...
        'template', 'devCCF-P04-20um_template_volume.npy', ...
        'annotation', 'devCCF-P04-20um_annotation_volume.npy', ...
        'structure_tree', 'structure_tree_safe_devCCF.csv', ...
        'brain', 'P04\root.mat' ...
    ), ...
    'P14', struct( ...
        'template', 'devCCF-P14-20um_template_volume.npy', ...
        'annotation', 'devCCF-P14-20um_annotation_volume.npy', ...
        'structure_tree', 'structure_tree_safe_devCCF.csv', ...
        'brain', 'P14\root.mat' ...
    ) ...
);

% Get the directory where AP_histology.m is located
ap_histology_path = which('AP_histology'); % Find the function file
if isempty(ap_histology_path)
    error('❌ AP_histology.m not found in the MATLAB path. Ensure it is accessible.');
end
ap_histology_dir = fileparts(ap_histology_path);

atlas_settings_path = fullfile(ap_histology_dir, 'atlas_paths.mat');

% Save the struct as a MAT file
save(atlas_settings_path, 'templates');

disp(['✅ Atlas paths saved to ', atlas_settings_path]);
